## 162주 데이터 cross-sectional 샘플

In [1]:
# 패키지 임포트

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [3]:
# 데이터 불러오기

df = pd.read_csv('./ML_training_sample_3y.csv')
print(df.shape)
df

(8562, 179)

,public_id,category,total_purchase_invoice,total_purchase_card,sales_05,sales_611,sales_1217,sales_1823,weekend_sales,delivery_ratio,...,sales_week_155,sales_week_156,sales_week_157,sales_week_158,sales_week_159,sales_week_160,sales_week_161,sales_week_162,Cluster,new_label
0,5603,hof,0,0,0.039652,0.005124,0.378657,0.576716,0.445805,0.000000,...,0.000012,0.000008,0.000019,0.000016,0.000006,0.000011,0.000010,0.000009,Cluster 6,DDZ
1,13669,normal,546176314,0,0.000220,0.066154,0.602418,0.331593,0.100270,0.000000,...,0.000038,0.000034,0.000049,0.000053,0.000051,0.000035,0.000043,0.000050,Cluster 1,DDZ
2,23391,normal,0,0,0.081190,0.001964,0.015893,0.900833,0.167602,0.000000,...,0.000005,0.000002,0.000004,0.000004,0.000008,0.000002,0.000009,0.000005,Cluster 1,DDZ
3,43054,normal,0,0,0.000000,0.167766,0.832234,0.000000,0.153770,0.000000,...,0.000025,0.000021,0.000022,0.000017,0.000017,0.000022,0.000028,0.000023,Cluster 6,DDZ
4,44372,normal,423410818,0,0.047391,0.032522,0.405609,0.514522,0.290172,0.150480,...,0.000039,0.000041,0.000039,0.000041,0.000024,0.000043,0.000043,0.000037,Cluster 6,DDZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8557,99833155,cafe,0,0,0.000000,0.133353,0.657803,0.208555,0.359538,0.000000,...,0.000038,0.000039,0.000045,0.000042,0.000041,0.000039,0.000030,0.000039,Cluster 4,DDZ
8558,99843037,normal,67917809,0,0.000000,0.030299,0.678922,0.290838,0.534464,0.000000,...,0.000017,0.000023,0.000021,0.000022,0.000023,0.000011,0.000034,0.000036,Cluster 1,DDZ
8559,99896819,normal,0,0,0.000000,0.039267,0.743508,0.217487,0.141436,0.000000,...,0.000022,0.000020,0.000020,0.000028,0.000014,0.000025,0.000023,0.000033,Cluster 6,DDZ
8560,99926315,hof,291425958,0,0.143515,0.000061,0.054424,0.801515,0.342108,0.000000,...,0.000104,0.000110,0.000103,0.000111,0.000079,0.000097,0.000090,0.000092,Cluster 6,DDZ
8561,99929262,normal,1331827752,0,0.006321,0.181399,0.481451,0.330518,0.150000,0.399234,...,0.000072,0.000066,0.000066,0.000063,0.000056,0.000054,0.000062,0.000068,Cluster 6,DDZ

In [4]:
# 타겟 변수 설정

df_y = df['new_label']
df_y

0       DDZ
1       DDZ
2       DDZ
3       DDZ
4       DDZ
       ...
8557    DDZ
8558    DDZ
8559    DDZ
8560    DDZ
8561    DDZ
Name: new_label, Length: 8562, dtype: object

In [6]:
# 인풋 변수 설정

df_x = df.drop(['public_id', 'category', 'new_label', 'Cluster'] , axis = 1)

print(df_x.shape)
df_x

(8562, 175)

,total_purchase_invoice,total_purchase_card,sales_05,sales_611,sales_1217,sales_1823,weekend_sales,delivery_ratio,new_customer_ratio,delivery_link,...,sales_week_153,sales_week_154,sales_week_155,sales_week_156,sales_week_157,sales_week_158,sales_week_159,sales_week_160,sales_week_161,sales_week_162
0,0,0,0.039652,0.005124,0.378657,0.576716,0.445805,0.000000,0.662099,0,...,0.000015,0.000017,0.000012,0.000008,0.000019,0.000016,0.000006,0.000011,0.000010,0.000009
1,546176314,0,0.000220,0.066154,0.602418,0.331593,0.100270,0.000000,0.565593,0,...,0.000051,0.000044,0.000038,0.000034,0.000049,0.000053,0.000051,0.000035,0.000043,0.000050
2,0,0,0.081190,0.001964,0.015893,0.900833,0.167602,0.000000,0.473154,0,...,0.000002,0.000002,0.000005,0.000002,0.000004,0.000004,0.000008,0.000002,0.000009,0.000005
3,0,0,0.000000,0.167766,0.832234,0.000000,0.153770,0.000000,0.620619,0,...,0.000021,0.000027,0.000025,0.000021,0.000022,0.000017,0.000017,0.000022,0.000028,0.000023
4,423410818,0,0.047391,0.032522,0.405609,0.514522,0.290172,0.150480,0.462350,1,...,0.000046,0.000039,0.000039,0.000041,0.000039,0.000041,0.000024,0.000043,0.000043,0.000037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8557,0,0,0.000000,0.133353,0.657803,0.208555,0.359538,0.000000,0.439957,0,...,0.000038,0.000030,0.000038,0.000039,0.000045,0.000042,0.000041,0.000039,0.000030,0.000039
8558,67917809,0,0.000000,0.030299,0.678922,0.290838,0.534464,0.000000,0.909345,0,...,0.000019,0.000018,0.000017,0.000023,0.000021,0.000022,0.000023,0.000011,0.000034,0.000036
8559,0,0,0.000000,0.039267,0.743508,0.217487,0.141436,0.000000,0.572881,0,...,0.000015,0.000010,0.000022,0.000020,0.000020,0.000028,0.000014,0.000025,0.000023,0.000033
8560,291425958,0,0.143515,0.000061,0.054424,0.801515,0.342108,0.000000,0.920701,0,...,0.000108,0.000101,0.000104,0.000110,0.000103,0.000111,0.000079,0.000097,0.000090,0.000092
8561,1331827752,0,0.006321,0.181399,0.481451,0.330518,0.150000,0.399234,0.523099,1,...,0.000066,0.000082,0.000072,0.000066,0.000066,0.000063,0.000056,0.000054,0.000062,0.000068

### XGB 모델

In [7]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 데이터 로드 및 전처리

X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3, random_state=42)

# XGBoost 모델 학습
model = xgb.XGBClassifier(random_state=42)

label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

y_train_encoded = to_categorical(y_train_encoded, num_classes=6)
y_test_encoded = to_categorical(y_test_encoded, num_classes=6)

model.fit(X_train, y_train_encoded)

y_pred = model.predict(X_test)

y_pred_classes = np.argmax(y_pred, axis = 1)
y_test_classes = np.argmax(y_test_encoded, axis = 1)

print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))
print("\nClassification Report:\n", classification_report(y_test_classes, y_pred_classes))

NameError: name 'LabelEncoder' is not defined

### MLP 모델

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np


# label별 가중치 설정 (데이터가 많을수록 가중치 낮음)
weight_for_0 = ( 1/ 1004)*(1004+6269+723+81+879+1086)/6
weight_for_1 = ( 1/ 6269)*(1004+6269+723+81+879+1086)/6
weight_for_2 = (1 / 723)*(1004+6269+723+81+879+1086)/6
weight_for_3 = (1 / 81)*(1004+6269+723+81+879+1086)/6
weight_for_4 = (1 / 879)*(1004+6269+723+81+879+1086)/6
weight_for_5 = (1 / 1086)*(1004+6269+723+81+879+1086)/6

class_weights_dic = {0: weight_for_0, 1: weight_for_1, 2:weight_for_2, 
                    3: weight_for_3, 4:weight_for_4, 5: weight_for_5}


X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3, random_state=191, stratify = df_y)


label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

y_train_encoded = to_categorical(y_train_encoded, num_classes=6)
y_test_encoded = to_categorical(y_test_encoded, num_classes=6)

# 과대 샘플링 적용시
#smote = SMOTE(random_state=12)
#X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train_encoded)

# 과소 샘플링 적용시
#rus = RandomUnderSampler(random_state=12)
#X_train_rus, y_train_rus = rus.fit_resample(X_train, y_train_encoded)

# 신경망 모델 구성
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(6, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train_encoded, epochs=10, batch_size=24, validation_split=0.2, class_weight = class_weights_dic)

# 모델 평가
y_pred = model.predict(X_test)

# 원-핫 인코딩된 예측 결과를 정수 레이블로 변환
y_pred_classes = np.argmax(y_pred, axis=1)

# 실제 레이블이 원-핫 인코딩 형태인 경우, 정수 레이블로 변환
y_test_classes = np.argmax(y_test_encoded, axis=1)

# 성능 메트릭 계산
print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))
print("f1:", f1_score(y_test_classes, y_pred_classes, average = 'weighted'))

2026-01-28 02:07:24.809599: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1769566048.840722  289591 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1
I0000 00:00:1769566048.841614  289591 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 11100 MB memory:  -> device: 1, name: NVIDIA TITAN Xp, pci bus id: 0000:04:00.0, compute capability: 6.1
I0000 00:00:1769566048.842394  289591 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 11100 MB memory:  -> device: 2, name: NVIDIA TITAN Xp, pci bus id: 0000:83:00.0, compute capability: 6.1
I0000 00:00:1769566048.843195  289591 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 11100 MB memory:  -> device: 3, name: NVIDIA TITAN Xp, pci bus id: 0000:84:00.0, compute capability: 6.1
2026-01-28 02:07:29.422770: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.427136: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.430161: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.435793: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.439802: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.444779: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.449952: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.454546: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.460022: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.465402: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.470429: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.475431: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2026-01-28 02:07:29.480820: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.

Epoch 1/10

2026-01-28 02:07:31.853413: I external/local_xla/xla/service/service.cc:163] XLA service 0x7f8c34003ad0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-01-28 02:07:31.853444: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA TITAN Xp, Compute Capability 6.1
2026-01-28 02:07:31.853452: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (1): NVIDIA TITAN Xp, Compute Capability 6.1
2026-01-28 02:07:31.853459: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (2): NVIDIA TITAN Xp, Compute Capability 6.1
2026-01-28 02:07:31.853466: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (3): NVIDIA TITAN Xp, Compute Capability 6.1
2026-01-28 02:07:32.093247: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-01-28 02:07:32.688318: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002
2026-01-28 02:07:36.031263: W tensorflow/core/framework/op_kernel.cc:1855] OP_REQUIRES failed at xla_ops.cc:590 : UNAVAILABLE: No PTX compilation provider is available. Neither ptxas/nvlink nor nvjtlink is available. As a fallback you can enable JIT compilation in the CUDA driver via the flag `--xla_gpu_unsafe_fallback_to_driver_on_ptxas_not_found`. Details:
 - Has NvJitLink support: LibNvJitLink is not supported (disabled during compilation).
 - Has NvPtxCompiler support: LibNvPtxCompiler is not supported (disabled during compilation).
 - Parallel compilation support is desired: 0
 - ptxas_path: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - ptxas_version: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - nvlink_path: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - nvlink_version: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - Driver compilation is enabled: 0

2026-01-28 02:07:36.031425: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: UNAVAILABLE: No PTX compilation provider is available. Neither ptxas/nvlink nor nvjtlink is available. As a fallback you can enable JIT compilation in the CUDA driver via the flag `--xla_gpu_unsafe_fallback_to_driver_on_ptxas_not_found`. Details:
 - Has NvJitLink support: LibNvJitLink is not supported (disabled during compilation).
 - Has NvPtxCompiler support: LibNvPtxCompiler is not supported (disabled during compilation).
 - Parallel compilation support is desired: 0
 - ptxas_path: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - ptxas_version: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - nvlink_path: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - nvlink_version: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - Driver compilation is enabled: 0

	 [[{{node StatefulPartitionedCall}}]]

UnavailableError: Graph execution error:

Detected at node StatefulPartitionedCall defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start

  File "/home/hyeoky98/miniforge/lib/python3.12/asyncio/base_events.py", line 645, in run_forever

  File "/home/hyeoky98/miniforge/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once

  File "/home/hyeoky98/miniforge/lib/python3.12/asyncio/events.py", line 88, in _run

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 614, in shell_main

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_shell

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 366, in execute_request

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 827, in execute_request

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 458, in do_execute

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3123, in run_cell

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3178, in _run_cell

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3400, in run_cell_async

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3641, in run_ast_nodes

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code

  File "/tmp/ipykernel_289591/3803005754.py", line 52, in <module>

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 399, in fit

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 241, in function

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 154, in multi_step_on_iterator

  File "/home/hyeoky98/miniforge/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 125, in wrapper

No PTX compilation provider is available. Neither ptxas/nvlink nor nvjtlink is available. As a fallback you can enable JIT compilation in the CUDA driver via the flag `--xla_gpu_unsafe_fallback_to_driver_on_ptxas_not_found`. Details:
 - Has NvJitLink support: LibNvJitLink is not supported (disabled during compilation).
 - Has NvPtxCompiler support: LibNvPtxCompiler is not supported (disabled during compilation).
 - Parallel compilation support is desired: 0
 - ptxas_path: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - ptxas_version: Couldn't find a suitable version of ptxas. The following locations were considered: ./cuda_sdk_lib/bin/ptxas, /home/hyeoky98/miniforge/bin/ptxas, /home/hyeoky98/miniforge/condabin/ptxas, /usr/local/sbin/ptxas, /usr/local/bin/ptxas, /usr/sbin/ptxas, /usr/bin/ptxas, /sbin/ptxas, /bin/ptxas, /usr/games/ptxas, /usr/local/games/ptxas, /snap/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvcc/bin/ptxas, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/ptxas, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/ptxas, ipykern/cuda_nvcc/bin/ptxas, ipykern/cuda_nvdisasm/bin/ptxas, ipykern/nvidia_nvshmem/bin/ptxas, bin/ptxas, /usr/local/cuda/bin/ptxas, /opt/cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/ptxas, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/ptxas
 - nvlink_path: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - nvlink_version: Couldn't find a suitable version of nvlink. The following locations were considered: ./cuda_sdk_lib/bin/nvlink, /home/hyeoky98/miniforge/bin/nvlink, /home/hyeoky98/miniforge/condabin/nvlink, /usr/local/sbin/nvlink, /usr/local/bin/nvlink, /usr/sbin/nvlink, /usr/bin/nvlink, /sbin/nvlink, /bin/nvlink, /usr/games/nvlink, /usr/local/games/nvlink, /snap/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvcc/bin/nvlink, ipykernel_launcher.runfiles/cuda_nvdisasm/bin/nvlink, ipykernel_launcher.runfiles/nvidia_nvshmem/bin/nvlink, ipykern/cuda_nvcc/bin/nvlink, ipykern/cuda_nvdisasm/bin/nvlink, ipykern/nvidia_nvshmem/bin/nvlink, bin/nvlink, /usr/local/cuda/bin/nvlink, /opt/cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda/bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../bin/nvlink, /home/hyeoky98/miniforge/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../../bin/nvlink
 - Driver compilation is enabled: 0

	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_1709]

In [437]:
# 예시 배열

# 고유한 값과 그 개수 계산
unique_values, counts = np.unique(y_pred_classes, return_counts=True)

# 결과 출력
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")

Value: 0, Count: 29
Value: 1, Count: 1231
Value: 2, Count: 1302
Value: 3, Count: 7

In [438]:
from sklearn.metrics import classification_report

# 각 클래스에 대한 성능 지표 계산
report = classification_report(y_test_classes, y_pred_classes)
print(report)

              precision    recall  f1-score   support

           0       0.14      0.01      0.02       403
           1       0.71      0.48      0.57      1837
           2       0.06      0.41      0.10       179
           3       0.00      0.00      0.00        37
           4       0.00      0.00      0.00       113

    accuracy                           0.37      2569
   macro avg       0.18      0.18      0.14      2569
weighted avg       0.53      0.37      0.42      2569

C:\Users\KAIST\kcd\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KAIST\kcd\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KAIST\kcd\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

### GridSearchCV를 이용한 최적 하이퍼파라미터 찾기

In [327]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

# train_test_split 함수에 stratify 매개변수를 y로 설정
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3, random_state=11, stratify=df_y)


# 레이블 인코딩 및 원-핫 인코딩
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)
y_train_encoded = to_categorical(y_train_encoded, num_classes=4)
y_test_encoded = to_categorical(y_test_encoded, num_classes=4)

# 모델 생성 함수
def create_model(activation, optimizer):
    model = Sequential()
    model.add(Dense(128, activation=activation, input_shape=(X_train.shape[1],)))
    model.add(Dense(64, activation=activation))
    model.add(Dense(32, activation=activation))
    model.add(Dense(4, activation='softmax'))  # 클래스 개수에 맞게 조정
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy', f1_score])
    return model

# KerasClassifier 설정
model = KerasClassifier(model=create_model, verbose=0)

# 하이퍼파라미터 그리드 설정
param_grid = {
    'model__activation': ['relu', 'tanh'],
    'model__optimizer': ['adam', 'rmsprop', 'sgd'],
    'batch_size': [24, 32],
    'epochs': [10, 20]
}

# 그리드 탐색
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_result = grid.fit(X_train, y_train_encoded)

# 결과 출력
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.673351 using {'batch_size': 24, 'epochs': 10, 'model__activation': 'tanh', 'model__optimizer': 'adam'}
0.619439 (0.102896) with: {'batch_size': 24, 'epochs': 10, 'model__activation': 'relu', 'model__optimizer': 'adam'}
0.509607 (0.219326) with: {'batch_size': 24, 'epochs': 10, 'model__activation': 'relu', 'model__optimizer': 'rmsprop'}
0.673351 (0.010042) with: {'batch_size': 24, 'epochs': 10, 'model__activation': 'tanh', 'model__optimizer': 'adam'}
0.673351 (0.010042) with: {'batch_size': 24, 'epochs': 10, 'model__activation': 'tanh', 'model__optimizer': 'rmsprop'}
0.434078 (0.098530) with: {'batch_size': 24, 'epochs': 20, 'model__activation': 'relu', 'model__optimizer': 'adam'}
0.508691 (0.208802) with: {'batch_size': 24, 'epochs': 20, 'model__activation': 'relu', 'model__optimizer': 'rmsprop'}
0.673351 (0.010042) with: {'batch_size': 24, 'epochs': 20, 'model__activation': 'tanh', 'model__optimizer': 'adam'}
0.673351 (0.010042) with: {'batch_size': 24, 'epochs': 20, 'model__activation': 'tanh', 'model__optimizer': 'rmsprop'}
0.508384 (0.120001) with: {'batch_size': 32, 'epochs': 10, 'model__activation': 'relu', 'model__optimizer': 'adam'}
0.581929 (0.115538) with: {'batch_size': 32, 'epochs': 10, 'model__activation': 'relu', 'model__optimizer': 'rmsprop'}
0.673351 (0.010042) with: {'batch_size': 32, 'epochs': 10, 'model__activation': 'tanh', 'model__optimizer': 'adam'}
0.673351 (0.010042) with: {'batch_size': 32, 'epochs': 10, 'model__activation': 'tanh', 'model__optimizer': 'rmsprop'}
0.418106 (0.164222) with: {'batch_size': 32, 'epochs': 20, 'model__activation': 'relu', 'model__optimizer': 'adam'}
0.463057 (0.195765) with: {'batch_size': 32, 'epochs': 20, 'model__activation': 'relu', 'model__optimizer': 'rmsprop'}
0.673351 (0.010042) with: {'batch_size': 32, 'epochs': 20, 'model__activation': 'tanh', 'model__optimizer': 'adam'}
0.673351 (0.010042) with: {'batch_size': 32, 'epochs': 20, 'model__activation': 'tanh', 'model__optimizer': 'rmsprop'}

## 108주 Time-Series 샘플

In [9]:
df = pd.read_csv('D:/credit/training/sample/ML_training_sample_2y.csv')
print(df.shape)
df

(14347, 125)

,public_id,category,total_purchase_invoice,total_purchase_card,sales_05,sales_611,sales_1217,sales_1823,weekend_sales,delivery_ratio,...,sales_week_101,sales_week_102,sales_week_103,sales_week_104,sales_week_105,sales_week_106,sales_week_107,sales_week_108,Cluster,new_label
0,5603,hof,0,0,0.039652,0.005124,0.378657,0.576716,0.445805,0.000000,...,0.000001,0.000003,0.000017,0.000010,0.000005,0.000003,0.000003,0.000003,Cluster 2,DDY
1,13669,normal,546176314,0,0.000220,0.066154,0.602418,0.331593,0.100270,0.000000,...,0.000033,0.000042,0.000044,0.000037,0.000042,0.000043,0.000042,0.000041,Cluster 0,DDZ
2,23391,normal,0,0,0.081190,0.001964,0.015893,0.900833,0.167602,0.000000,...,0.000005,0.000007,0.000004,0.000006,0.000004,0.000006,0.000008,0.000007,Cluster 0,DDZ
3,29487,normal,1094882997,0,0.000000,0.136402,0.613110,0.250610,0.118537,0.037343,...,0.000163,0.000192,0.000212,0.000225,0.000218,0.000216,0.000250,0.000222,Cluster 1,DUY
4,38882,normal,601444151,435330,0.000840,0.031092,0.427647,0.540504,0.302683,1.912412,...,0.000056,0.000082,0.000032,0.000043,0.000089,0.000044,0.000030,0.000040,Cluster 3,DDZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14342,93670971,normal,0,0,0.024560,0.110400,0.517920,0.347200,0.292598,11.122636,...,0.000023,0.000033,0.000018,0.000029,0.000029,0.000025,0.000028,0.000032,Cluster 8,UUX
14343,93673242,normal,0,0,0.000000,0.008986,0.509662,0.481304,0.216298,0.000000,...,0.000098,0.000081,0.000083,0.000101,0.000074,0.000092,0.000125,0.000105,Cluster 0,DDZ
14344,93679442,normal,0,0,0.000000,0.143796,0.512898,0.343184,0.280041,0.000000,...,0.000022,0.000029,0.000029,0.000032,0.000025,0.000030,0.000026,0.000036,Cluster 0,DDZ
14345,93682837,normal,1066190555,0,0.116937,0.001441,0.173378,0.708333,0.323784,4.017071,...,0.000189,0.000164,0.000169,0.000179,0.000166,0.000176,0.000171,0.000197,Cluster 4,DDZ
14346,93683816,normal,253593936,0,0.056855,0.000081,0.132419,0.809919,0.248042,0.000000,...,0.000044,0.000040,0.000027,0.000025,0.000039,0.000035,0.000033,0.000021,Cluster 2,UUX

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# 'feature1' 열에 대해 Min-Max Scaling 적용
df['total_purchase_invoice'] = scaler.fit_transform(df[['total_purchase_invoice']])
df['total_purchase_card'] = scaler.fit_transform(df[['total_purchase_card']])

df

,public_id,category,total_purchase_invoice,total_purchase_card,sales_05,sales_611,sales_1217,sales_1823,weekend_sales,delivery_ratio,...,sales_week_101,sales_week_102,sales_week_103,sales_week_104,sales_week_105,sales_week_106,sales_week_107,sales_week_108,Cluster,new_label
0,5603,hof,0.000000,0.000702,0.039652,0.005124,0.378657,0.576716,0.445805,0.000000,...,0.000001,0.000003,0.000017,0.000010,0.000005,0.000003,0.000003,0.000003,Cluster 2,DDY
1,13669,normal,0.041023,0.000702,0.000220,0.066154,0.602418,0.331593,0.100270,0.000000,...,0.000033,0.000042,0.000044,0.000037,0.000042,0.000043,0.000042,0.000041,Cluster 0,DDZ
2,23391,normal,0.000000,0.000702,0.081190,0.001964,0.015893,0.900833,0.167602,0.000000,...,0.000005,0.000007,0.000004,0.000006,0.000004,0.000006,0.000008,0.000007,Cluster 0,DDZ
3,29487,normal,0.082237,0.000702,0.000000,0.136402,0.613110,0.250610,0.118537,0.037343,...,0.000163,0.000192,0.000212,0.000225,0.000218,0.000216,0.000250,0.000222,Cluster 1,DUY
4,38882,normal,0.045174,0.001520,0.000840,0.031092,0.427647,0.540504,0.302683,1.912412,...,0.000056,0.000082,0.000032,0.000043,0.000089,0.000044,0.000030,0.000040,Cluster 3,DDZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14342,93670971,normal,0.000000,0.000702,0.024560,0.110400,0.517920,0.347200,0.292598,11.122636,...,0.000023,0.000033,0.000018,0.000029,0.000029,0.000025,0.000028,0.000032,Cluster 8,UUX
14343,93673242,normal,0.000000,0.000702,0.000000,0.008986,0.509662,0.481304,0.216298,0.000000,...,0.000098,0.000081,0.000083,0.000101,0.000074,0.000092,0.000125,0.000105,Cluster 0,DDZ
14344,93679442,normal,0.000000,0.000702,0.000000,0.143796,0.512898,0.343184,0.280041,0.000000,...,0.000022,0.000029,0.000029,0.000032,0.000025,0.000030,0.000026,0.000036,Cluster 0,DDZ
14345,93682837,normal,0.080082,0.000702,0.116937,0.001441,0.173378,0.708333,0.323784,4.017071,...,0.000189,0.000164,0.000169,0.000179,0.000166,0.000176,0.000171,0.000197,Cluster 4,DDZ
14346,93683816,normal,0.019047,0.000702,0.056855,0.000081,0.132419,0.809919,0.248042,0.000000,...,0.000044,0.000040,0.000027,0.000025,0.000039,0.000035,0.000033,0.000021,Cluster 2,UUX

In [13]:
# 시간 변수 선택
X = df.iloc[:, 14:-2]
y = df['new_label']

# time-invarying 변수 선택
static_feature = df[['total_purchase_invoice', 'total_purchase_card',
                'sales_05', 'sales_611', 'sales_1823', 'sales_1217', 'weekend_sales', 'delivery_ratio',
               'new_customer_ratio', 'delivery_link', 'franchise1', 'open_after', 'category']]

,sales_week_0,sales_week_1,sales_week_2,sales_week_3,sales_week_4,sales_week_5,sales_week_6,sales_week_7,sales_week_8,sales_week_9,...,sales_week_99,sales_week_100,sales_week_101,sales_week_102,sales_week_103,sales_week_104,sales_week_105,sales_week_106,sales_week_107,sales_week_108
0,0.000054,0.000047,0.000039,0.000014,0.000017,0.000071,0.000071,0.000081,0.000071,0.000049,...,0.000004,0.000006,0.000001,0.000003,0.000017,0.000010,0.000005,0.000003,0.000003,0.000003
1,0.000113,0.000113,0.000113,0.000113,0.000184,0.000179,0.000155,0.000131,0.000103,0.000094,...,0.000047,0.000037,0.000033,0.000042,0.000044,0.000037,0.000042,0.000043,0.000042,0.000041
2,0.000010,0.000012,0.000013,0.000011,0.000011,0.000027,0.000020,0.000032,0.000017,0.000016,...,0.000003,0.000005,0.000005,0.000007,0.000004,0.000006,0.000004,0.000006,0.000008,0.000007
3,0.000029,0.000247,0.000268,0.000257,0.000243,0.000274,0.000243,0.000239,0.000302,0.000301,...,0.000208,0.000201,0.000163,0.000192,0.000212,0.000225,0.000218,0.000216,0.000250,0.000222
4,0.000112,0.000162,0.000167,0.000164,0.000171,0.000136,0.000129,0.000082,0.000133,0.000115,...,0.000037,0.000037,0.000056,0.000082,0.000032,0.000043,0.000089,0.000044,0.000030,0.000040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14342,0.000017,0.000040,0.000030,0.000036,0.000027,0.000049,0.000043,0.000037,0.000027,0.000025,...,0.000034,0.000027,0.000023,0.000033,0.000018,0.000029,0.000029,0.000025,0.000028,0.000032
14343,0.000084,0.000130,0.000153,0.000209,0.000119,0.000119,0.000096,0.000098,0.000114,0.000094,...,0.000093,0.000098,0.000098,0.000081,0.000083,0.000101,0.000074,0.000092,0.000125,0.000105
14344,0.000104,0.000276,0.000263,0.000265,0.000243,0.000152,0.000157,0.000145,0.000125,0.000141,...,0.000025,0.000022,0.000022,0.000029,0.000029,0.000032,0.000025,0.000030,0.000026,0.000036
14345,0.000016,0.000058,0.000074,0.000070,0.000067,0.000073,0.000059,0.000065,0.000051,0.000055,...,0.000182,0.000184,0.000189,0.000164,0.000169,0.000179,0.000166,0.000176,0.000171,0.000197
14346,0.000400,0.000923,0.000848,0.000820,0.000707,0.000621,0.000677,0.000588,0.000552,0.000486,...,0.000032,0.000031,0.000044,0.000040,0.000027,0.000025,0.000039,0.000035,0.000033,0.000021

In [15]:
# 업종변수 더미변수화

category_dummy = pd.get_dummies(static_feature['category'], prefix='category')
static_feature1 = pd.concat([static_feature, category_dummy], axis=1)
static_feature1['category_cafe'] = static_feature1['category_cafe'].astype(int)
static_feature1['category_hof'] = static_feature1['category_hof'].astype(int)
static_feature1['category_normal'] = static_feature1['category_normal'].astype(int)

static_feature1.drop('category', axis=1, inplace=True)

In [17]:
# Long format으로 전환

expanded_static_feature = np.repeat(static_feature1.values[:, np.newaxis, :], 109, axis=1)
combined_data = np.concatenate((X.values[:, :, np.newaxis], expanded_static_feature), axis=2)

In [19]:
X_reshaped = combined_data
X_reshaped

array([[[5.37000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [4.70000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [3.92000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        ...,
        [2.73000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [3.34000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [3.17000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00]],

       [[1.12583000e-04, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.12583000e-04, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.12583000e-04, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        ...,
        [4.30000000e-05, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [4.17000000e-05, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [4.12000000e-05, 4.10233138e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00]],

       [[1.00000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.24000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.35000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        ...,
        [5.85000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [7.51000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [6.85000000e-06, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00]],

       ...,

       [[1.04392000e-04, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [2.75821000e-04, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [2.62608000e-04, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        ...,
        [3.00000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [2.62000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [3.59000000e-05, 0.00000000e+00, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00]],

       [[1.59000000e-05, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [5.75000000e-05, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [7.44000000e-05, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        ...,
        [1.76042000e-04, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.70891000e-04, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [1.96622000e-04, 8.00815938e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00]],

       [[4.00281000e-04, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [9.23037000e-04, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [8.48124000e-04, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        ...,
        [3.47000000e-05, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [3.30000000e-05, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [2.06000000e-05, 1.90474456e-02, 7.01852882e-04, ...,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]])

In [20]:
#데이터 형태 확인

X_reshaped.shape

(14347, 109, 16)

In [24]:
# 테스트셋, 트레인셋 데이터 나누기

X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y, test_size=0.3, random_state=42, stratify = y)

In [25]:
# 클래스 개수 확인

y_train.value_counts()

new_label
DDZ    6269
UUX    1086
DDY    1004
UDZ     879
DUY     723
UDY      81
Name: count, dtype: int64

In [28]:
# 타겟변수에 대한 원-핫 인코딩
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

y_train_encoded = to_categorical(y_train_encoded, num_classes=6)
y_test_encoded = to_categorical(y_test_encoded, num_classes=6)

### 1D CNN 모델

In [34]:
from tensorflow.keras.layers import ConvLSTM2D, Flatten
from sklearn.metrics import f1_score

# 합성곱 LSTM 모델 구성
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense

# label별 가중치 설정 (데이터가 많을수록 가중치 낮음)
weight_for_0 = ( 1/ 1004)*(1004+6269+723+81+879+1086)/6
weight_for_1 = ( 1/ 6269)*(1004+6269+723+81+879+1086)/6
weight_for_2 = (1 / 723)*(1004+6269+723+81+879+1086)/6
weight_for_3 = (1 / 81)*(1004+6269+723+81+879+1086)/6
weight_for_4 = (1 / 879)*(1004+6269+723+81+879+1086)/6
weight_for_5 = (1 / 1086)*(1004+6269+723+81+879+1086)/6

class_weights_dic = {0: weight_for_0, 1: weight_for_1, 2:weight_for_2, 
                    3: weight_for_3, 4:weight_for_4, 5: weight_for_5}
# 모델 구성
model = Sequential()

# 1D 컨볼루션 레이어 추가
# 예시 매개변수: 64개의 필터, 커널 크기 3
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(109, 16)))

# 1D 맥스 풀링 레이어 추가
model.add(MaxPooling1D(pool_size=3))

# Flatten 레이어 추가
model.add(Flatten())

# 완전 연결 레이어 추가
model.add(Dense(32, activation='relu'))


# 출력 레이어 추가
model.add(Dense(6, activation='softmax')) 

# 모델 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 학습
model.fit(X_train, y_train_encoded, epochs=10, batch_size=24, validation_split=0.2, class_weight = class_weights_dic)

# 모델 평가
y_pred = model.predict(X_test)

# 원-핫 인코딩된 예측 결과를 정수 레이블로 변환
y_pred_classes = np.argmax(y_pred, axis=1)

# 실제 레이블이 원-핫 인코딩 형태인 경우, 정수 레이블로 변환
y_test_classes = np.argmax(y_test_encoded, axis=1)

# 성능 메트릭 계산
print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))
print("f1:", f1_score(y_test_classes, y_pred_classes, average = 'weighted'))

Epoch 1/10

C:\Users\KAIST\kcd\lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(

335/335 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1173 - loss: 63.7456 - val_accuracy: 0.0786 - val_loss: 1.7909
Epoch 2/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0986 - loss: 1.7739 - val_accuracy: 0.0961 - val_loss: 1.7897
Epoch 3/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1271 - loss: 1.7764 - val_accuracy: 0.0961 - val_loss: 1.7878
Epoch 4/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2556 - loss: 1.7751 - val_accuracy: 0.0961 - val_loss: 1.7881
Epoch 5/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1499 - loss: 1.8035 - val_accuracy: 0.0961 - val_loss: 1.7878
Epoch 6/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0865 - loss: 1.8130 - val_accuracy: 0.0961 - val_loss: 1.7845
Epoch 7/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1091 - loss: 1.8493 - val_accuracy: 0.6162 - val_loss: 1.7842
Epoch 8/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2081 - loss: 1.8330 - val_accuracy: 0.6162 - val_loss: 1.7839
Epoch 9/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5115 - loss: 1.7120 - val_accuracy: 0.6162 - val_loss: 1.7845
Epoch 10/10
335/335 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2591 - loss: 1.7561 - val_accuracy: 0.0961 - val_loss: 1.7871
135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.09988385598141696
f1: 0.018141524000848695

## LSTM 모델

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

weight_for_0 = ( 1/ 1004)*(1004+6269+723+81+879+1086)/6
weight_for_1 = ( 1/ 6269)*(1004+6269+723+81+879+1086)/6
weight_for_2 = (1 / 723)*(1004+6269+723+81+879+1086)/6
weight_for_3 = (1 / 81)*(1004+6269+723+81+879+1086)/6
weight_for_4 = (1 / 879)*(1004+6269+723+81+879+1086)/6
weight_for_5 = (1 / 1086)*(1004+6269+723+81+879+1086)/6


#array([0, 1, 2]), array([370, 977, 795])

class_weights_dic = {0: weight_for_0, 1: weight_for_1, 2:weight_for_2, 
                    3: weight_for_3, 4:weight_for_4, 5: weight_for_5}

# 모델 구성
model = Sequential()
model.add(LSTM(128, activation='relu', input_shape=(109, 16)))  # 109 시간 단계, 1개의 특성
model.add(Dense(64, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(y_train_encoded.shape[1], activation='softmax'))  # 클래스 개수에 맞게 출력층 조정

# 모델 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 학습
history = model.fit(X_train, y_train_encoded, epochs=10, batch_size=32, validation_split=0.2)

# 가중치 적용 시
#history = model.fit(X_train, y_train_encoded, epochs=10, batch_size=50, validation_split=0.2, class_weight = class_weights_dic)

# 모델 평가
y_pred = model.predict(X_test)

# 원-핫 인코딩된 예측 결과를 정수 레이블로 변환
y_pred_classes = np.argmax(y_pred, axis=1)

# 실제 레이블이 원-핫 인코딩 형태인 경우, 정수 레이블로 변환
y_test_classes = np.argmax(y_test_encoded, axis=1)

# 성능 메트릭 계산
print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))
print("f1:", f1_score(y_test_classes, y_pred_classes, average = 'weighted'))

Epoch 1/10

C:\Users\KAIST\kcd\lib\site-packages\keras\src\layers\rnn\rnn.py:205: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

252/252 ━━━━━━━━━━━━━━━━━━━━ 9s 32ms/step - accuracy: 0.5992 - loss: 909.3050 - val_accuracy: 0.6162 - val_loss: 1.4096
Epoch 2/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - accuracy: 0.6256 - loss: 1.3523 - val_accuracy: 0.6162 - val_loss: 1.2677
Epoch 3/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6244 - loss: 1.2428 - val_accuracy: 0.6162 - val_loss: 1.2350
Epoch 4/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6302 - loss: 1.2047 - val_accuracy: 0.6162 - val_loss: 1.2278
Epoch 5/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6234 - loss: 1.2127 - val_accuracy: 0.6162 - val_loss: 1.2256
Epoch 6/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6275 - loss: 1.2019 - val_accuracy: 0.6162 - val_loss: 1.2245
Epoch 7/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6256 - loss: 1.2043 - val_accuracy: 0.6162 - val_loss: 1.2243
Epoch 8/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6221 - loss: 1.2112 - val_accuracy: 0.6162 - val_loss: 1.2242
Epoch 9/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - accuracy: 0.6268 - loss: 1.1993 - val_accuracy: 0.6162 - val_loss: 1.2240
Epoch 10/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - accuracy: 0.6219 - loss: 1.2122 - val_accuracy: 0.6162 - val_loss: 1.2242
135/135 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step
Accuracy: 0.6241579558652729
f1: 0.47972323438500813